eureka:
  client:
    service-url:
      defaultZone: http://localhost:9527/eureka/
server:
  port: 8765
spring:
  application:
    name: service-hi
#  datasource:
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://172.16.10.44:3306/spring-cloud-auth?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
#      username: dev
#      password: NHdev2015
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:9700/users/current
    client:
      id: tt
      client-secret: 123456
      access-token-uri: http://localhost:9700/oauth/token
      grant-type: refresh_token,password
      scope: test


