server:
  port: 9800

spring:
  application:
    name: swagger-service

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:9527/eureka
zuul:
  routes:
    service-C:
      service-id: service-C
      path: /service-C/**
  strip-prefix: true
