server:
  port: 9600
spring:
  application:
    name: zuul-service
  redis:
    host: 47.100.245.161
    port: 6379

zuul:
  ignored-services: '*'
  host:
    connect-timeout-millis: 2000
    socket-timeout-millis: 2000
  routes:
    user-service:
      path: /user-service/**
      serviceId: user-service
      sensitiveHeaders: "*"
    service-A:
      path: /service-AA/**
      serviceId: service-AA
      sensitiveHeaders: "*"

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:9527/eureka