server:
  port: 9530
spring:
  application:
    name: service-C
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:9527/eureka

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:9700/users/current
    client:
      id: tt
      client-secret: 123456
      access-token-uri: http://localhost:9700/oauth/token
      grant-type: password, refresh_token
      scope: test