server:
  port: 9528
spring:
  application:
    name: service-AA
  redis:
    host: 47.100.245.161
    port: 6379
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:9527/eureka